language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
    - VERSION_TO_COVER="6.3"
  matrix:
    - RACKET_VERSION="6.1.1"
      CATALOG_VERSION="6.1.1"
    - RACKET_VERSION="6.2"
      CATALOG_VERSION="6.2"
    - RACKET_VERSION="6.2.1"
      CATALOG_VERSION="6.2.1"
    - RACKET_VERSION="6.3"
      CATALOG_VERSION="6.3"
    - RACKET_VERSION="HEAD"
      CATALOG_VERSION="6.3"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD"
           CATALOG_VERSION="6.3"

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - export VERSION_SPECIFIC_CATALOG="http://download.racket-lang.org/releases/${CATALOG_VERSION}/catalog/"
  - raco pkg config --set catalogs $VERSION_SPECIFIC_CATALOG http://pkgs.racket-lang.org http://planet-compats.racket-lang.org
  - raco pkg install --deps search-auto cover
  - raco pkg install --deps search-auto cover-coveralls

install:
 - raco pkg install --deps search-auto $TRAVIS_BUILD_DIR

script:
 - raco test $TRAVIS_BUILD_DIR
 - if [ "${VERSION_TO_COVER}" == "${RACKET_VERSION}" ]; then raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage .; fi
